Repository fourkitchens/fourkitchens-karaoke, pull requests merged in 2022-10, with the labels that each got.

#13 adds main menu
  config/main/block.block.mainnavigation_2.yml
  web/themes/custom/karaoke_2022/components/01-atoms/images/icons/_icon.twig
  web/themes/custom/karaoke_2022/components/01-atoms/text/text/02-blockquote.twig
  web/themes/custom/karaoke_2022/components/01-atoms/text/text/blockquote.yml
  web/themes/custom/karaoke_2022/components/02-molecules/menus/_menu-item.twig
  web/themes/custom/karaoke_2022/components/02-molecules/menus/_menu-list.twig
  web/themes/custom/karaoke_2022/components/02-molecules/menus/main-menu/_00-main-menu.scss
  web/themes/custom/karaoke_2022/components/02-molecules/menus/main-menu/main-menu.twig
  web/themes/custom/karaoke_2022/components/02-molecules/menus/social/_social-menu-item.twig
  web/themes/custom/karaoke_2022/components/02-molecules/menus/social/social-menu.twig
  web/themes/custom/karaoke_2022/components/style.scss
  web/themes/custom/karaoke_2022/project.emulsify.json
Labels: Needs Review

#16 main menu cleanup
  config/main/block.block.mainnavigation_2.yml
  web/themes/custom/karaoke_2022/components/02-molecules/menus/main-menu/_00-main-menu.scss
  web/themes/custom/karaoke_2022/components/02-molecules/menus/main-menu/_03-main-menu-toggle.scss
  web/themes/custom/karaoke_2022/components/03-organisms/site/site-header/_site-header.scss
  web/themes/custom/karaoke_2022/components/style.scss
Labels: Needs Work

#20 Security Updates
  composer.json
  composer.lock
  config/main/core.extension.yml
  config/main/upgrade_status.settings.yml
  config/main/views.view.4k_song_book.yml
Labels: Needs Review

#19 Theme updates from Randy
  package-lock.json
  web/themes/custom/karaoke_2022/components/00-base/00-defaults/_03-mixins.scss
  web/themes/custom/karaoke_2022/components/01-atoms/buttons/_buttons.scss
  web/themes/custom/karaoke_2022/components/01-atoms/buttons/button-alt.yml
  web/themes/custom/karaoke_2022/components/01-atoms/buttons/button-coin.yml
  web/themes/custom/karaoke_2022/components/01-atoms/buttons/button.twig
  web/themes/custom/karaoke_2022/components/01-atoms/buttons/buttons.stories.js
  web/themes/custom/karaoke_2022/components/01-atoms/forms/_input.twig
  web/themes/custom/karaoke_2022/components/01-atoms/forms/checkbox/checkbox.twig
  web/themes/custom/karaoke_2022/components/01-atoms/forms/radio/radio.twig
  web/themes/custom/karaoke_2022/components/01-atoms/forms/select/select.twig
  web/themes/custom/karaoke_2022/components/01-atoms/forms/textfields/textfields.twig
  web/themes/custom/karaoke_2022/components/01-atoms/lists/_list.scss
  web/themes/custom/karaoke_2022/components/02-molecules/pager/pager.twig
  web/themes/custom/karaoke_2022/components/02-molecules/status/status.twig
  web/themes/custom/karaoke_2022/components/03-organisms/site/site-header/_site-header.scss
  web/themes/custom/karaoke_2022/components/_vars.scss
  web/themes/custom/karaoke_2022/components/style.scss
  web/themes/custom/karaoke_2022/images/mario-coin.gif
  web/themes/custom/karaoke_2022/karaokedesign.theme
  web/themes/custom/karaoke_2022/templates/form/bef-radios.html.twig
  web/themes/custom/karaoke_2022/templates/layout/page.html.twig
Labels: enhancement, Needs Review

#22 The awesome background is on top of everything.
  web/themes/custom/karaoke_2022/components/04-templates/_default.scss
Labels: Needs Review

#23 Logo work
  web/themes/custom/karaoke_2022/components/03-organisms/site/site-header/site-header.twig
  web/themes/custom/karaoke_2022/images/logo.png
  web/themes/custom/karaoke_2022/images/logo.svg
Labels: Needs Review

#24 Input Background Fix
  web/themes/custom/karaoke_2022/components/style.scss
Labels: Needs Review
